apiVersion: v1
kind: Service
metadata:
  name: sant-05
  namespace: argo
  labels:
    app: sant
    available: "true"
spec:
  type: NodePort
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 30024
      targetPort: 30024
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30024