apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: find-nodeport-
  namespace: argo
spec:
  entrypoint: find-nodeport
  templates:
  
  - name: find-nodeport
    steps:
    
    - - name: allocate-nodeports-1
        template: allocate
    - - name: pyspark-executor-1
        template: pyspark-1
        arguments: 
          parameters: 
          - name: nodeport1 
            value: "{{steps.allocate-nodeports-1.outputs.parameters.nodeport1}}"
          - name: nodeport2 
            value: "{{steps.allocate-nodeports-1.outputs.parameters.nodeport2}}"
    - - name: deallocate-nodeports-1
        template: deallocate
        arguments:
          parameters:
          - name: svcname01
            value: "{{steps.allocate-nodeports-1.outputs.parameters.svcname01}}"
          - name: svcname02
            value: "{{steps.allocate-nodeports-1.outputs.parameters.svcname02}}"

    - - name: allocate-nodeports-2
        template: allocate
    - - name: pyspark-executor-2
        template: pyspark-2
        arguments: 
          parameters: 
          - name: nodeport1 
            value: "{{steps.allocate-nodeports-1.outputs.parameters.nodeport1}}"
          - name: nodeport2 
            value: "{{steps.allocate-nodeports-1.outputs.parameters.nodeport2}}"
    - - name: deallocate-nodeports-2
        template: deallocate
        arguments:
          parameters:
          - name: svcname01
            value: "{{steps.allocate-nodeports-2.outputs.parameters.svcname01}}"
          - name: svcname02
            value: "{{steps.allocate-nodeports-2.outputs.parameters.svcname02}}"

  - name: allocate
    container:
      image: pinholuc/gut-sant:latest
      command: [python]
      args: [./find_nodeport_patch_selector.py]
    outputs:
      parameters:
      - name: svcname01
        valueFrom:
          path: /tmp/svcname1.txt
      - name: svcname02
        valueFrom:
          path: /tmp/svcname2.txt
      - name: nodeport1 
        valueFrom:
          path: /tmp/nodeport1.txt
      - name: nodeport2 
        valueFrom: 
          path: /tmp/nodeport2.txt

  - name: pyspark-1
    metadata:
      labels:
        user: x247451
    inputs:
      parameters:
      - name: nodeport1 
      - name: nodeport2
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["Mia & Sebastian meow meow"]
      env:
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: special-config
              key: ENVIRONMENT
        - name: SPARK_DRIVER_PORT 
          value: "{{inputs.parameters.nodeport1}}"
        - name: SPARK_BLOCKMANAGER_PORT 
          value: "{{inputs.parameters.nodeport2}}"
        - name: SPARK_DRIVER_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1 
              fieldPath: spec.nodeName
        - name: SPARK_DRIVER_BINDADDRESS 
          value: 0.0.0.0
    restartPolicy: Never

  - name: pyspark-2
    metadata:
      labels:
        user: x247451
    inputs:
      parameters:
      - name: nodeport1 
      - name: nodeport2
    container:
      image: pinholuc/gut-sant:latest
      command: [python]
      args: [./test_env.py]
      env:
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: special-config
              key: ENVIRONMENT
        - name: SPARK_DRIVER_PORT 
          value: "{{inputs.parameters.nodeport1}}"
        - name: SPARK_BLOCKMANAGER_PORT 
          value: "{{inputs.parameters.nodeport2}}"
        - name: SPARK_DRIVER_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1 
              fieldPath: spec.nodeName
        - name: SPARK_DRIVER_BINDADDRESS 
          value: 0.0.0.0
    restartPolicy: Never

              
  - name: deallocate
    inputs:
      parameters:
      - name: svcname01
      - name: svcname02
    container:
      image: pinholuc/gut-sant:latest
      command: [python]
      args: [./deallocate_nodeport.py]
      env:
        - name: SERVICE_NAME_01
          value: "{{inputs.parameters.svcname01}}"
        - name: SERVICE_NAME_02
          value: "{{inputs.parameters.svcname02}}"


