apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: find-nodeport-
  namespace: argo
spec:
  entrypoint: find-nodeport
  templates:
  
  - name: find-nodeport
    steps:
    - - name: allocate-nodeports
        template: allocate
    - - name: pyspark-executor
        onExit: deallocate
        template: pyspark

  - name: allocate
    container:
      image: pinholuc/gut-sant:latest
      command: [python]
      args: [./find_nodeport_patch_selector.py]

  - name: pyspark
    metadata:
      labels:
        user: x247451
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["py-spark notebook executed. Next step is to deallocate nodeports :)"]

  - name: deallocate
    container:
      image: pinholuc/gut-sant:latest
      command: [python]
      args: [./deallocate_nodeport.py]


